language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - android-sdk-license-.+
    - '.+'

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

branches:
  only:
    - master

script:
  - ./gradlew build
  - ./gradlew assembleRelease

before_deploy:
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/baseAdapter.apk

deploy:
  provider: releases
  api_key:
    secure: $REPO
  file: app/build/outputs/apk/baseAdapter.apk
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1

after_success:
  - bash <(curl -s https://codecov.io/bash)