language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleRelease

before_deploy:
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/baseAdapter.apk

deploy:
  provider: releases
  api_key:
    secure: $REPO
  file: app/build/outputs/apk/baseAdapter.apk
  skip_cleanup: true
  on:
    tags: true