language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $PWD/gradle-3.3/


android:
  components:
    - tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:


script:
  - ./gradlew assembleRelease